<?php


declare(strict_types=1);

namespace OpenFeature\Providers\Flipt;


class ResponseReasons {
    
    const UNKNOWN_EVALUATION_REASON = 'UNKNOWN_EVALUATION_REASON';
    const FLAG_DISABLED_EVALUATION_REASON = 'FLAG_DISABLED_EVALUATION_REASON';
    const MATCH_EVALUATION_REASON = 'MATCH_EVALUATION_REASON';
    const DEFAULT_EVALUATION_REASON = 'DEFAULT_EVALUATION_REASON';
}