<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema/v1/schema.proto

namespace Schema\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response body for object flag evaluation. used by the ResolveObject rpc.
 *
 * Generated from protobuf message <code>schema.v1.ResolveObjectResponse</code>
 */
class ResolveObjectResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The response value of the object flag evaluation, will be unset in the case of error.
     * NOTE: This structure will need to be decoded from google/protobuf/struct.proto before it is returned to the SDK
     *
     * Generated from protobuf field <code>.google.protobuf.Struct value = 1 [json_name = "value"];</code>
     */
    protected $value = null;
    /**
     * The reason for the given return value, see https://docs.openfeature.dev/docs/specification/types#resolution-details
     *
     * Generated from protobuf field <code>string reason = 2 [json_name = "reason"];</code>
     */
    protected $reason = '';
    /**
     * The variant name of the returned flag value.
     *
     * Generated from protobuf field <code>string variant = 3 [json_name = "variant"];</code>
     */
    protected $variant = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Struct $value
     *           The response value of the object flag evaluation, will be unset in the case of error.
     *           NOTE: This structure will need to be decoded from google/protobuf/struct.proto before it is returned to the SDK
     *     @type string $reason
     *           The reason for the given return value, see https://docs.openfeature.dev/docs/specification/types#resolution-details
     *     @type string $variant
     *           The variant name of the returned flag value.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema\V1\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * The response value of the object flag evaluation, will be unset in the case of error.
     * NOTE: This structure will need to be decoded from google/protobuf/struct.proto before it is returned to the SDK
     *
     * Generated from protobuf field <code>.google.protobuf.Struct value = 1 [json_name = "value"];</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getValue()
    {
        return $this->value;
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     * The response value of the object flag evaluation, will be unset in the case of error.
     * NOTE: This structure will need to be decoded from google/protobuf/struct.proto before it is returned to the SDK
     *
     * Generated from protobuf field <code>.google.protobuf.Struct value = 1 [json_name = "value"];</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->value = $var;

        return $this;
    }

    /**
     * The reason for the given return value, see https://docs.openfeature.dev/docs/specification/types#resolution-details
     *
     * Generated from protobuf field <code>string reason = 2 [json_name = "reason"];</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * The reason for the given return value, see https://docs.openfeature.dev/docs/specification/types#resolution-details
     *
     * Generated from protobuf field <code>string reason = 2 [json_name = "reason"];</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->reason = $var;

        return $this;
    }

    /**
     * The variant name of the returned flag value.
     *
     * Generated from protobuf field <code>string variant = 3 [json_name = "variant"];</code>
     * @return string
     */
    public function getVariant()
    {
        return $this->variant;
    }

    /**
     * The variant name of the returned flag value.
     *
     * Generated from protobuf field <code>string variant = 3 [json_name = "variant"];</code>
     * @param string $var
     * @return $this
     */
    public function setVariant($var)
    {
        GPBUtil::checkString($var, True);
        $this->variant = $var;

        return $this;
    }

}

