<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema/v1/schema.proto

namespace Schema\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response body for the EvenntStream stream response
 *
 * Generated from protobuf message <code>schema.v1.EventStreamResponse</code>
 */
class EventStreamResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * String key indicating the type of event that is being received, e.g. provider_ready or configuration_change
     *
     * Generated from protobuf field <code>string type = 1 [json_name = "type"];</code>
     */
    protected $type = '';
    /**
     * Object structure for use when sending relevant metadata to provide context to the event.
     * Can be left unset when it is not required.
     *
     * Generated from protobuf field <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     */
    protected $data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *           String key indicating the type of event that is being received, e.g. provider_ready or configuration_change
     *     @type \Google\Protobuf\Struct $data
     *           Object structure for use when sending relevant metadata to provide context to the event.
     *           Can be left unset when it is not required.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema\V1\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * String key indicating the type of event that is being received, e.g. provider_ready or configuration_change
     *
     * Generated from protobuf field <code>string type = 1 [json_name = "type"];</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * String key indicating the type of event that is being received, e.g. provider_ready or configuration_change
     *
     * Generated from protobuf field <code>string type = 1 [json_name = "type"];</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Object structure for use when sending relevant metadata to provide context to the event.
     * Can be left unset when it is not required.
     *
     * Generated from protobuf field <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getData()
    {
        return $this->data;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * Object structure for use when sending relevant metadata to provide context to the event.
     * Can be left unset when it is not required.
     *
     * Generated from protobuf field <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->data = $var;

        return $this;
    }

}

