<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema/v1/schema.proto

namespace Schema\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request body for string flag evaluation, used by the ResolveString rpc.
 *
 * Generated from protobuf message <code>schema.v1.ResolveStringRequest</code>
 */
class ResolveStringRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Flag key of the requested flag.
     *
     * Generated from protobuf field <code>string flag_key = 1 [json_name = "flagKey"];</code>
     */
    protected $flag_key = '';
    /**
     * Object structure describing the EvaluationContext used in the flag evaluation, see https://openfeature.dev/docs/reference/concepts/evaluation-context
     *
     * Generated from protobuf field <code>.google.protobuf.Struct context = 2 [json_name = "context"];</code>
     */
    protected $context = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $flag_key
     *           Flag key of the requested flag.
     *     @type \Google\Protobuf\Struct $context
     *           Object structure describing the EvaluationContext used in the flag evaluation, see https://openfeature.dev/docs/reference/concepts/evaluation-context
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema\V1\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * Flag key of the requested flag.
     *
     * Generated from protobuf field <code>string flag_key = 1 [json_name = "flagKey"];</code>
     * @return string
     */
    public function getFlagKey()
    {
        return $this->flag_key;
    }

    /**
     * Flag key of the requested flag.
     *
     * Generated from protobuf field <code>string flag_key = 1 [json_name = "flagKey"];</code>
     * @param string $var
     * @return $this
     */
    public function setFlagKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->flag_key = $var;

        return $this;
    }

    /**
     * Object structure describing the EvaluationContext used in the flag evaluation, see https://openfeature.dev/docs/reference/concepts/evaluation-context
     *
     * Generated from protobuf field <code>.google.protobuf.Struct context = 2 [json_name = "context"];</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getContext()
    {
        return $this->context;
    }

    public function hasContext()
    {
        return isset($this->context);
    }

    public function clearContext()
    {
        unset($this->context);
    }

    /**
     * Object structure describing the EvaluationContext used in the flag evaluation, see https://openfeature.dev/docs/reference/concepts/evaluation-context
     *
     * Generated from protobuf field <code>.google.protobuf.Struct context = 2 [json_name = "context"];</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->context = $var;

        return $this;
    }

}

